name: Run Scraper When scientists.csv Changes

on:
  push:
    # paths:
    #   - 'scientists.csv'    # Trigger only when this file is changed
  workflow_dispatch:        # Optional manual trigger

jobs:
  scrape:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run scraper inside scholar conda environment
      shell: bash -l {0}   # Important: loads your conda environment properly
      run: |
        conda activate scholar
        python google_scholar_paper_scraper.py \
          --csv-file "scientists.csv" \
          --column "Google Scholar Page" \
          --max-papers 2
